version: 2
jobs:
  polling-build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Jekyll Build
          command: echo bundle exec jekyll build
workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - polling-build
